name: Build and Run Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: ls
      - run: cd data-test
      - run: ls
      - run: cargo build --release
      - run: cargo run --release > output.txt
      - run: echo "output.txt" >> .gitignore
      - run: git add output.txt
      - run: git commit -m "Add output.txt"
      - run: git push
